"""
Script to read the predictions from whisper, and save the output in a .csv file to apply the grammar.

Example of use: python extract_preds_from_whisper_and_create_file_for_grammar.py --whisper_dir '/whisper_large/'
--save '/whisper_for_grammar/'
"""

import pandas as pd
import csv
from argparse import ArgumentParser, RawTextHelpFormatter

punctuations = '!?\":,/.;()[]'
punc_table = str.maketrans({key: None for key in punctuations})


def process_whisper_output(text):
    """
        Process the prediction from whisper model

        Arguments
        ---------
        text: str

        Returns
        -------
        The processed text.
    """
    t = text.replace('\n', '')
    a = t.translate(punc_table)
    b = a.replace('-', ' ')
    return ''.join(b.lower().strip())


def get_data_from_whisper(directory):
    """
        Read the data generated by whisper.

        Arguments
        ---------
        directory: str

        Returns
        -------
        The clip names and the predictions of the whisper model
    """
    clips, preds = [], []
    with open(directory + "out.txt", 'r') as f:
        csv_reader = csv.reader(f, delimiter='\t')
        for row in csv_reader:
            clips.append(row[0])
            preds.append(process_whisper_output(row[1]))
    return clips, preds


def save_whisper_pred_for_grammar(save, clips, preds):
    """
        Save whisper pred in a format readable to apply the grammar.

        Arguments
        ---------
        save: str
        clips: list
        preds: list
    """
    df = pd.DataFrame.from_dict(
        {'clips': clips, 'text': preds})
    csv_file = 'whisper_results.csv'
    df.to_csv(save + csv_file, index=False, header=True, sep='\t')


def main(args):
    clips, preds = get_data_from_whisper(args.whisper_dir)
    save_whisper_pred_for_grammar(args.save, clips, preds)


parser = ArgumentParser(
    description="Extract the predictions from whisper and save in a format readable to apply the grammar.",
    formatter_class=RawTextHelpFormatter)
parser.add_argument('--whisper_dir', type=str, required=True,
                    help="")
parser.add_argument('--save', type=str, required=True,
                    help="")
parser.set_defaults(func=main)
args = parser.parse_args()
args.func(args)
